# part of the panhandler application with docs at
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst

# unique snippet name
name: Configuring OSPFv3
# label used for menu selection
label: Configuring OSPFv3
description: Used to configure OSPFv3 once VR and IPv6 are created for the interfaces

# type of device configuration
# common types are panorama, panos, and template

type: panos
# preload static or default-based templates
extends:

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - Configuring OSPFv3

# variables used in the configuration templates
# type_hint defines the form field used by panhandler
# type_hints can be text, ip_address, or dropdown
variables:
  - name: redist_profile_name
    description: name of the redist_profile_name
    default: redist_ospfv3
    type_hint: text
  - name: ospfv3_area_id
    description: area id (as number)
    default: 1.1.1.1
    type_hint: numerial
  - name: ospfv3_enabled_interface
    description: interface participating in ospfv3
    default: ethernet1/1
    type_hint: text
  - name: ospfv3_router_id
    description: ospfv3_router_id
    default: 2.2.2.2
    type_hint: text
  - name: virtual_router_name
    description: virtual router name where ospfv3 needs to be enabled
    default: default
    type_hint: text
  # - name: tag_description
  #   description: tag description
  #   default: tag description
  #   type_hint: text
  # - name: tag_color
  #   description: tag color
  #   default: red
  #   type_hint: dropdown
  #   dd_list:
  #     - key: blue
  #       value: color3
  #     - key: green
  #       value: color2
  #     - key: orange
  #       value: color6
  #     - key: red
  #       value: color1

# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
snippets:
  - name: export_rules
    xpath: /config/devices/entry[@name='localhost.localdomain']/network/virtual-router/entry[@name='default']/protocol/redist-profile-ipv6
    file: redistribution_profile.xml
  - name: ospfv3_config
    xpath: /config/devices/entry[@name='localhost.localdomain']/network/virtual-router
    file: ospfv3.xml
  # - name: security_rules
  #   xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/rulebase/security/rules
  #   file: security_rules.xml